name: Build, Test, Push
on:
  push:
    branches: [main, develop, beta/*]
  issue_comment:
    types: [created]
  pull_request:
  workflow_dispatch:
    branches: [main, develop]
  
jobs:
  pull_request_trigger:
    runs-on: ubuntu-latest  
    steps:  
      - name: acknowledge readiness for QA
        uses: khan/pull-request-comment-trigger@master
        id: deploy-comment
        with:
          trigger: '/deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    outputs:
      triggered: ${{ steps.deploy-comment.outputs.triggered }}

  workflow_test:
    name: Test Workflow Triggers
    needs: [pull_request_trigger]
    runs-on: ubuntu-latest
    steps:
      - name: echo me echo
        if: needs.pull_request_trigger.outputs.triggered == 'true'
        run: |
          echo 'IT WERKED!'

  job_level_test:
    name: Test Job Level Triggers
    needs: [pull_request_trigger]
    if: needs.pull_request_trigger.outputs.triggered == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Job level test
        run: |
          echo 'Job level test success'

