name: Input Test
on:
  workflow_dispatch:
    inputs:
      git_sha:
        description: The full-length sha of a git commit.
        required: false
  
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      ROLLBACK_SHA: ${{ github.event.inputs.git_sha }}
    if: ${{ env.ROLLBACK_SHA }}
    steps:
      - name: echo me echo
        run: |
          echo 'IT WERKED!'
